import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import FirebasePersistence from "@/lib/components/firebasepersistence";
import FirebaseAuthListener from "@/lib/components/FirebaseAuthListener";
import { UserProvider } from "@/lib/components/usercontent"; // Import the UserProvider

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--poppins",
});

export const metadata: Metadata = {
  title: "BlancBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable}`} suppressHydrationWarning>
      <body className="font-poppins " suppressHydrationWarning>
        <FirebasePersistence />
        <FirebaseAuthListener />
        <UserProvider>
          {" "}
          {/* Wrap children with UserProvider */}
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
